name: Prod build and deployment
on:
  push:
    branches:
      - 'main'
jobs:
  BuildSimulation:
    # TODO abort this workflow if the git user triggered it is not the release manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify Current User Is Release Manager
        run: |
          echo Verifying Current User Is "${{ github.actor }}"
          if [[ "${{ github.actor }}" != "Arinmaz" ]]; then
            echo "ABORTING... Current User '${{ github.actor }}' is not The Release Manager."
            exit 1
          fi
          echo Current User is the release Manager.
      - name: Build
        run: |
          echo building and packing and app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo deploying into Test env